spring:
  application:
    name: api-gateway
server:
  port: 5200
zuul:
  routes:
    app-buy:
      path:  /api-buy/**
      serviceId: ticket-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://yp:123@localhost:1111/eureka,http://yp:123@localhost:1112/eureka


